### ISSUE TITLE
메모리에 Array를 생성하는 경우 메모리 할당을 해줘야합니다.

### ISSUE THREAD

**Issue by DoodlesOnMyFood** [DoodlesOnMyFood/Prediction_market#1]
erc20.sol 및 erc201.sol에 있는 market_ids함수에 uint[] result을 선언 할 때 다음과 같이 선언해야합니다.

function market_ids() public view returns (uint8[] memory){
        uint8[] memory result = new uint8[](_market_ids.length);
        for (uint256 i = 0; i < _market_ids.length; i++){
            result[i] = _market_ids[i];
        }
        return result;
    }

storage형 array에는 별도로 메모리할당이 필요하지 않으나 memory형은 메모리할당하지 않을시 revert합니다.

**Comment by MUNMUN-M** [comment]
수정했습니다. 감사합니다.
