### ISSUE TITLE
manager.sol에 있는 usableMarketId함수가 정상적으로 작동하지 않습니다.

### ISSUE THREAD

**Issue by DoodlesOnMyFood** [DoodlesOnMyFood/Prediction_market#2]
이 함수도 아까 기존에 있던 issue, array 메모리할당이 필요합니다. 그러나 별도로 메모리 할당하더라도 remix의 경우 정상적으로 반환하지 않는 경우를 볼 수 있습니다.(어쩌면 remix자체의 버그일 수 있음. revert하지 않으며 오히려 블록체인이 멈추는 현상이 발생)
정확히 왜 그런지 모르겠으나 루프 변수를 256에서 25로 낮추면 정상적으로 작동할 수 있음.

안되는 코드 : 
![image](https://user-images.githubusercontent.com/57210973/99715771-a2625800-2aea-11eb-99c3-8d0739586fba.png)

실행 가능한 코드 : 
![image](https://user-images.githubusercontent.com/57210973/99715948-d3428d00-2aea-11eb-8480-f8cb64ba0eb7.png)

왠지 잘 모르겠으나 깃허브 이슈에 탭 반영 잘 안되서 이미지도 첨부합니다.

function usableMarketId() external view onlyOwner returns (uint8[] memory){
        uint8[] memory result = new uint8[](25);
        uint8 counter;
        for (uint8 i = 0; i < 25 ; i++) {
            if (is_over_distribute[i] == false) {
                result[counter] = i;
                counter++;
            }
        }
        return result;
    }

**Comment by MUNMUN-M** [comment]
수정되었습니다.
루프 안에 i 의 크기를 잘못 선택해서 오류가 발생했습니다. i가 255까지 나타낼 수 있는데 i<256 에 걸리려면 i가 256까지는 가야 제약에 걸립니다.
그래서 지금은 uint16으로 수정했습니다. 감사합니다!
