### ISSUE TITLE
tradeToken에 있는 expireCheck의 if 부등호가 반대인 것 같습니다.

### ISSUE THREAD

**Issue by DoodlesOnMyFood** [DoodlesOnMyFood/Prediction_market#3]
실제로 현시점의 unix timestamp보다 큰 값을(미래 값)으로 market_id 생성하면 해당 market_id에 거래 생성 불가능합니다.

**Comment by MUNMUN-M** [comment]
제가 의도한 것은 expirationDateOf(이벤트의 결과가 나오는 날)가 미래이므로 지금(block.timestamp)값보다 커야지만 토큰거래를 할 수 있는 것이었습니다. 
제가 다음과 같이 간단한 테스트를 했을 때는 통과가 되었는데 혹시 더 큰 값으로 expireDateOf를 설정하신 다음에 해주실 수 있을까요?
![image](https://user-images.githubusercontent.com/73881222/99764154-c8feae00-2b3f-11eb-9780-915f96d15b00.png)

`pragma solidity ^0.7.0;

 contract WithdrawalContract{
    
    uint256 expire;
    
    modifier e() {
        require (expire >= block.timestamp, "expire");
        _;
    }
    
    function b(uint256 _e) public{
        expire = _e;
    }
    
    
    function c() public view e() returns (bool){
        if (expire >= block.timestamp){
            return true;
        }
        return false;
    }
    
}

`
타임스탬프는 이 사이트를 참조했습니다.
https://www.unixtimestamp.com/index.php
