### ISSUE TITLE
withdrawalContract에 더하기 오류

### ISSUE THREAD

**Issue by DoodlesOnMyFood** [DoodlesOnMyFood/Prediction_market#4]
addToBalance나 addToOwnerPW의 경우 pendingWithdrawls[msg.sender].add(msg.value) 같은 형태를 사용하지만,

add함수의 경우 assignment하지 않기 때문에 충천을해도 잔고가 0인 현상이 일어납니다.

pendingWithdrawls[msg.sender] = pendingWithdrawls[msg.sender].add(msg.value);

와 같은 형태로 바꿔야합니다.

**Comment by DoodlesOnMyFood** [comment]
이러한 함수들이 다수 존재합니다. 이중 몇개는 view함수로 지정되어 있으나 view는 블로체인 storage를 변경할 수 없기 때문에 이러한 형태로 바꾸신다면 view 키워드를 제거하십시오.

**Comment by MUNMUN-M** [comment]
수정했습니다. 감사합니다.
